version: '3.8'

services:
  your_application:
    image: com.example/demo:1.0-SNAPSHOT  # Adjust to your actual image name and tag
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # Optional: Set Spring profile if needed
    depends_on:
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:8.0.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
